# Generated by Django 4.1.1 on 2022-10-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.TextField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
