# Generated by Django 3.2.12 on 2022-10-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbno',
            field=models.IntegerField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.TextField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.TextField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
