# Generated by Django 3.2.12 on 2022-11-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0003_auto_20221024_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('jobe_type', models.CharField(max_length=50)),
                ('jobe_category', models.TextField(max_length=25)),
                ('location', models.TextField(max_length=70)),
                ('description', models.TextField(max_length=100)),
                ('salary_posted', models.IntegerField(max_length=15)),
            ],
        ),
    ]
