# Generated by Django 3.2.12 on 2022-11-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0004_advertisements_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
