# Generated by Django 3.2.12 on 2022-11-21 10:32

from django.db import migrations, models
import subapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0006_alter_advertisements_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(blank=True, upload_to=subapp.models.Advertisements.nameFile),
        ),
    ]
